// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCumLBJTFbe_1q78J2pvLggHqHdxYQE8Qk',
    appId: '1:944786199143:web:b9a7b64247ed00a9583ac2',
    messagingSenderId: '944786199143',
    projectId: 'test-project-2760f',
    authDomain: 'test-project-2760f.firebaseapp.com',
    storageBucket: 'test-project-2760f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-oX9nL7uYw-5AeqPRvkt6r-BHj7JwTY',
    appId: '1:944786199143:android:4391b7f84e03528b583ac2',
    messagingSenderId: '944786199143',
    projectId: 'test-project-2760f',
    storageBucket: 'test-project-2760f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXaRaSl0mXlKp4eXPeKs6JJDSywGP8DcQ',
    appId: '1:944786199143:ios:b099a427a1efd848583ac2',
    messagingSenderId: '944786199143',
    projectId: 'test-project-2760f',
    storageBucket: 'test-project-2760f.appspot.com',
    iosBundleId: 'com.example.fitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXaRaSl0mXlKp4eXPeKs6JJDSywGP8DcQ',
    appId: '1:944786199143:ios:9bec526fc4543f11583ac2',
    messagingSenderId: '944786199143',
    projectId: 'test-project-2760f',
    storageBucket: 'test-project-2760f.appspot.com',
    iosBundleId: 'com.example.fitapp.RunnerTests',
  );
}
